# Generated by Django 4.2.5 on 2023-09-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caloriesinput',
            old_name='user',
            new_name='user_id',
        ),
    ]
