# Generated by Django 4.2.5 on 2023-09-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_caloriesinput_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caloriesinput',
            old_name='user_id',
            new_name='user',
        ),
    ]
