# Generated by Django 4.2.5 on 2023-09-19 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_caloriesinput_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriesinput',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 19)),
        ),
    ]
